Get article comments
good4something-6/BE-NEWS-PROJECT pull request #6
Opened 2022-03-31 08:49 UTC by good4something-6

2022-03-31 09:35 UTC, HeatherEver reviewed
Looks really good! Just a couple of small changes to make!

2022-03-31 09:35 UTC, HeatherEver commented on __tests__/app.test.js
> +const { test, beforeEach, afterAll } = require("@jest/globals");
Think these lines have auto imported - if they have just delete them before they cause issues!

2022-03-31 09:35 UTC, HeatherEver commented on __tests__/app.test.js
> +        });
it appears you have no status 200 tests for your PATCH request?

2022-03-31 09:35 UTC, HeatherEver commented on __tests__/app.test.js
> +    test("404 article_id provided is not valid type", () => {
Change the status code in the test description 😄

2022-03-31 11:12 UTC, dentednerd commented on __tests__/app.test.js
> +require("jest-sorted");
You don't need to require `jest-sorted` here.

2022-03-31 11:12 UTC, dentednerd commented on __tests__/app.test.js
>      test("200 - valid article id is provided and votes updates by 1 correctly", () => {
Conventionally, we put happy path tests above sad path tests!

2022-03-31 11:13 UTC, dentednerd commented on __tests__/app.test.js
> +          expect(articles).toBeSorted({ key: "created_at", descending: true });
Much better!

2022-03-31 11:13 UTC, dentednerd commented on models/articles.model.js
> +  //return pullArticleById(article_id)
You won't need this comment anymore.

2022-03-31 11:14 UTC, dentednerd commented on models/articles.model.js
> +              msg: "NO MESSAGE IS PASSED FOR 200+ ERRORS (NO BODY)",
200 statuses aren't error statuses. 204 No Content is still a success status, so Promise.reject isn't appropriate here.

2022-03-31 11:15 UTC, dentednerd reviewed
A few changes left to make!

2022-03-31 12:02 UTC, xmenbteam requested changes
Speak after lunch!

2022-03-31 12:02 UTC, xmenbteam commented on models/articles.model.js
> +        .then((result) => {
This needs to be two separate functions. This function should get all the comments relating to an article, but not the article itself. That's for getARticleById to do!

2022-03-31 15:33 UTC, xmenbteam requested changes
Nice! Just a few bits :)

2022-03-31 15:33 UTC, xmenbteam commented on __tests__/app.test.js
>          });
Topics should be an array... How do we test for this?

2022-03-31 15:33 UTC, xmenbteam commented on controllers/article.controllers.js
> +  pushArticleComments,
Confusing names for your functions - have a look at my naming conventions document please!

2022-03-31 15:33 UTC, xmenbteam commented on models/articles.model.js
>      .query(`SELECT * FROM articles WHERE article_id = $1;`, [article_id])
This needs to have all the comment_count stuff in it as well!

2022-03-31 15:33 UTC, xmenbteam commented on models/articles.model.js
> +exports.pullArticleComments = (article_id) => {
This function is using the comments table, so should be in comments.model.js

2022-03-31 15:33 UTC, xmenbteam commented on models/articles.model.js
>    return db
Again, should be in comments.model.js

2022-04-01 09:30 UTC, HeatherEver reviewed
Looks good Mark, just make sure you're testing for errors 😄

2022-04-01 09:30 UTC, HeatherEver commented on __tests__/app.test.js
>          });
This is still isn't testing for an array specifically, have a look into .toBeArray(

2022-04-01 09:30 UTC, HeatherEver commented on __tests__/app.test.js
> +    });
need to add a couple of tests for errors here
think about incorrect article id, non existent and invalid

2022-04-01 09:30 UTC, HeatherEver commented on __tests__/app.test.js
> +          });
Need some error testing for POST comment
invalid article id 
invalid comment body
invalid comment username
incorrect path

2022-04-01 09:30 UTC, HeatherEver commented on __tests__/app.test.js
>        users.forEach((user) => {
Need an error test for this too for incorrect path

2022-04-01 13:01 UTC, P-Copley commented on models/comments.models.js
> +exports.fetchArticleCommentsSIMPLE = (article_id) => {
Do you use this function or is it left over from working things out?

2022-04-01 13:45 UTC, merged